stages:
  - build

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/

build:
  stage: build
  only:
    - master
  script:
    - npm install
    - npm run build
#    - cp -r dist/* /mnt/www/
  tags: 
    - erabbit-client-pc-vue3