stages:
  - build

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/

build:
  stage: build
  only:
    - master
  script:
#    - cnpm set registry https://registry.npm.taobao.org
    - cnpm install --progress=false
    - npm run build
    - cp -r dist/* /home/erabbit-ci/
  tags: 
    - erabbit-client-pc-vue3