stages:
  - build

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/

build:
  stage: build
  only:
    - master
  script:
    - yarn
    - yarn run build
    - rm -rf /home/erabbit-client-vue3/dist
    - mkdir /home/erabbit-client-vue3/dist
    - cp -r dist/* /home/erabbit-client-vue3/dist
  tags: 
    - erabbit-client-pc-vue3